class GroceryList:
    def __init__(self):
        self.grocery_list = grocery_items = [
            "2% reduced-fat milk",
            "Large white eggs",
            "Sliced white bread",
            "Long-grain white rice",
            "Spaghetti",
            "Corn flakes",
            "All-purpose flour",
            "Granulated white sugar",
            "Table salt",
            "Ground black pepper",
            "Salted butter",
            "Mild cheddar cheese",
            "Vanilla-flavored yogurt",
            "Fresh tomatoes",
            "Bananas",
            "Chicken thighs",
            "Ground beef (80% lean)",
            "Boneless pork chops",
            "Salmon fillets",
            "Hickory-smoked bacon",
            "Pork sausages",
            "Beef hot dogs",
            "Frozen mixed vegetables",
            "Frozen mixed berries",
            "Vanilla ice cream",
            "Pepperoni pizza",
            "Chicken noodle soup",
            "Green beans",
            "Canned peaches in syrup",
            "Creamy peanut butter",
            "Strawberry jam",
            "Tomato ketchup",
            "Yellow mustard",
            "Regular mayonnaise",
            "Ranch dressing",
            "Olive oil",
            "Balsamic vinegar",
            "Chunk light tuna in water",
            "Kidney beans",
            "Basmati rice",
            "Marinara sauce",
            "Flour tortillas",
            "Taco seasoning mix",
            "Potato chips",
            "Medium-spicy salsa",
            "Baking powder",
            "Baking soda",
            "Semi-sweet chocolate chips",
            "Almonds",
            "Raisins",
            "Ground coffee",
            "Black tea bags",
            "Cola",
            "Bottled water",
            "Orange juice",
            "Soy sauce",
            "Ramen noodles",
            "Old-fashioned oats",
            "Diced tomatoes",
            "Chicken broth",
            "Fresh parsley",
            "Ground cinnamon",
            "Pancake mix",
            "Pure maple syrup",
            "Waffle mix",
            "Applesauce baby food",
            "Size 3 diapers",
            "Liquid laundry detergent",
            "Toilet paper rolls",
            "Paper towel roll"
        ]

        self.test_list = ["2% reduced-fat milk",
            "Large white eggs",
            "Sliced white bread",
            "Long-grain white rice"]

