name: Grocery Web Scraper Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11  # Specify the Python version you want to use



    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: |
        cd GroceryScraper
        poetry install

    - name: Run tests with coverage
      run: |
        cd GroceryScraper
        poetry run coverage run --source=. -m pytest

    - name: Generate coverage report
      run: |
        cd GroceryScraper
        poetry run coverage report

    - name: Save coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./GroceryScraper/htmlcov  # Adjust this path based on your coverage report location

    - name: Generate HTML coverage report
      run: |
        cd GroceryScraper
        poetry run coverage html